package dotty
package tools
package dotc

import org.junit.{AfterClass, Test}
import vulpix._

import scala.concurrent.duration._

class FromTastyTests extends ParallelTesting {
  import TestConfiguration._
  import FromTastyTests._

  // Test suite configuration --------------------------------------------------

  def maxDuration = 30.seconds
  def numberOfSlaves = 5
  def safeMode = Properties.testsSafeMode
  def isInteractive = SummaryReport.isInteractive
  def testFilter = Properties.testsFilter


  @Test def posTestFromTasty: Unit = {
    // Can be reproduced with
    // > sbt
    // > dotc -Ythrough-tasty -Ycheck:all <source>

    implicit val testGroup: TestGroup = TestGroup("posTestFromTasty")
    compileTastyInDir("tests/pos", defaultOptions,
      blacklist = Set(
        // Wrong number of arguments (only on bootstrapped)
        "i3130b.scala",

        // Missing position
        "collections_1.scala",

        // MatchError in SymDenotation.sourceModule on a ThisType
        "t3612.scala",

        // Fails on MacOS
        "annot-bootstrap.scala",
      ),
      decompilationBlacklist = Set(

        // Constant(Symbol)
        "desugar.scala",
        "sip23-symbols.scala",
        "t389.scala",
        "t4812.scala",
        "t4579.scala",

        // assertion failed: asTerm called on not-a-Term val <none>
        "cls.scala",
        "escapes2.scala",
        "existentials-harmful.scala",
        "constrs.scala",
        "i2051.scala",
        "i2663.scala",
        "i1318.scala",
        "gui.scala",
        "i1756.scala",
        "i2218.scala",
        "objXfun.scala",
        "printTest.scala",
        "paramAliases.scala",
        "michel1.scala",
        "nested.scala",
        "philippe3.scala",
        "t115.scala",
        "t0017.scala",
        "t0055.scala",
        "t1075.scala",
        "t267.scala",
        "t247.scala",
        "t1226.scala",
        "t0039.scala",
        "t8324.scala",
        "t4062.scala",
        "t8177b.scala",
        "t803.scala",
        "t3071.scala",
        "t8177.scala",
        "tangledCompanion.scala",
        "templateParents.scala",
        "t5384.scala",
        "t9795.scala",
        "alias.scala",
        "t0032.scala",
        "supercalls.scala",
        "i1776.scala",
        "i3638.scala",
        "i618.scala",

        // scala.MatchError: Type.RecursiveType
        "i3647.scala",

        // Stackoverflow
        "avoid.scala",
        "i1047.scala",
        "i1181.scala",

        // scala.MatchError: EmptyTree
        "depfuntype.scala",
        "compound.scala",
        "implicit-dep.scala",
        "refinedSubtyping.scala",
        "zoo2.scala",
        "typers.scala",
        "apply-equiv.scala",
        "projections.scala",
        "lookuprefined.scala",

        // NPE
        "i2888.scala",
        "tcpoly_overloaded.scala",
        "tcpoly_boundedmonad.scala",
        "tcpoly_checkkinds_mix.scala",

        // scala.MatchError: This
        "infersingle.scala",

      ),
      recompilationBlacklist = Set(
        "aliasNew",
        "andtypes",
        "annot",
        "annotations2",
        "annotDepMethType",
        "approximateUnion",
        "arrays2",
        "assignments",
        "blockescapes",
        "bounds",
        "boundspropagation",
        "bynamefuns",
        "capturedVars",
        "collections",
        "compile",
        "depmet_1_pos",
        "depmet_implicit_tpbetareduce",
        "devalify",
        "eff-compose",
        "erased-asInstanceOf",
        "erased-extension-method",
        "erased-lub",
        "ErasureAnd",
        "Fileish",
        "flow",
        "gadt-eval",
        "hk",
        "hklower",
        "hkrange",
        "ho-implicits",
        "i1044",
        "i1365",
        "i143",
        "i1447",
        "i1665",
        "i1753",
        "i1754",
        "i1757",
        "i1786",
        "i1790",
        "i1812",
        "i1812b",
        "i1857",
        "i1870",
        "i1976",
        "i1990a",
        "i2064",
        "i2112",
        "i2146",
        "i2152",
        "i2198",
        "i2239",
        "i2250",
        "i2278",
        "i2300",
        "i2397",
        "i2468",
        "i2554",
        "i2570",
        "i2637",
        "i2671",
        "i2672",
        "i2749",
        "i2788",
        "i2906",
        "i2980",
        "i2997",
        "i3000",
        "i3067",
        "i3083",
        "i3139",
        "i3149",
        "i3207",
        "i3246",
        "i3248",
        "i3264",
        "i3352",
        "i3381",
        "i3462",
        "i3544",
        "i3564",
        "i3598",
        "i3606",
        "i3636",
        "i3637",
        "i3658",
        "i3669",
        "i3692",
        "i3965",
        "i3965a",
        "i3976",
        "i4032",
        "i4125",
        "i4196",
        "i4345",
        "i4375",
        "i4380a",
        "i4419",
        "i4590",
        "i4753",
        "i503",
        "i530-import-symbolic",
        "i583a",
        "i801",
        "i884",
        "i94-nada",
        "i941",
        "i966",
        "i996",
        "implicitFuns",
        "implicitNums",
        "implicits2",
        "infer",
        "inferred",
        "inline-apply",
        "inline-i1773",
        "interfaceObject",
        "intersection",
        "isApplicableSafe",
        "Iter2",
        "Iterable",
        "javaConversions-2.10-ambiguity",
        "javaConversions-2.10-regression",
        "Labels",
        "lazyValsSepComp",
        "Meter",
        "mixins",
        "nameddefaults",
        "NoCyclicReference",
        "opassign",
        "Orderings",
        "overloaddefault",
        "overloaded_ho_fun",
        "package-case",
        "param-depmeth",
        "patmat",
        "patmatSeq",
        "Patterns",
        "patterns3",
        "pets",
        "phantom-Eq",
        "phantom-Evidence",
        "poly-inheritance",
        "pos-bug1210",
        "quote-0",
        "quote-lift",
        "quote-liftable",
        "Result",
        "sammy_single",
        "sams",
        "scala-singleton",
        "seq-ordering",
        "SI-4012-a",
        "SI-7638",
        "SI-7638a",
        "simplelists",
        "simplesams",
        "spec-example1",
        "spec-multiplectors",
        "spec-sealed",
        "spec-simple",
        "spec-sparsearray-old",
        "spec-traits",
        "spliceTest",
        "strawman-i79",
        "superacc",
        "t0036",
        "t0095",
        "t0231",
        "t0305",
        "t1001",
        "t1014",
        "t1035",
        "t1050",
        "t1053",
        "t1085",
        "t1136",
        "t1147",
        "t1208",
        "t1236",
        "t1237",
        "t1279a",
        "t1280",
        "t1438",
        "t1957",
        "t1974",
        "t2038",
        "t2066",
        "t2130-1",
        "t2130-2",
        "t2168",
        "t2179",
        "t2310",
        "t2368",
        "t2399",
        "t2435",
        "t2441pos",
        "t2444",
        "t2454",
        "t2484",
        "t2503",
        "t2610",
        "t2613",
        "t2660",
        "t2664",
        "t2698",
        "t2712-3",
        "t2712-5",
        "t2712-7",
        "t2910",
        "t295",
        "t3037",
        "t3152",
        "t3174",
        "t3177",
        "t3343",
        "t3374",
        "t3384",
        "t3430",
        "t3528",
        "t3672",
        "t3777",
        "t3836",
        "t3862",
        "t3866",
        "t3960",
        "t4018",
        "t404",
        "t4063",
        "t4070b",
        "t4114",
        "t4176b",
        "t4502",
        "t4842",
        "t5033",
        "t5082",
        "t5178",
        "t530",
        "t5330",
        "t5330c",
        "t5359",
        "t5399",
        "t5406",
        "t5702-pos-infix-star",
        "t5720-ownerous",
        "t5727",
        "t573",
        "t577",
        "t578",
        "t5809",
        "t5877",
        "t5877b",
        "t5900a",
        "t5958",
        "t6022b",
        "t6084",
        "t6089b",
        "t6123-explaintypes-implicits",
        "t6162-inheritance",
        "t6499",
        "t6562",
        "t6575a",
        "t6575b",
        "t661",
        "t6797",
        "t6921",
        "t6925b",
        "t6948",
        "t6994",
        "t703",
        "t7033",
        "t7226",
        "t7315",
        "t7322",
        "t7329",
        "t7426",
        "t7475a",
        "t7475b",
        "t7475d",
        "t7517",
        "t7694",
        "t7753",
        "t7785",
        "t7815",
        "t7864",
        "t789",
        "t7902",
        "t7944",
        "t7983",
        "t802",
        "t8046",
        "t8046b",
        "t8046c",
        "t8170",
        "t8177a",
        "t8207",
        "tcpoly_infer_easy",
        "tcpoly_infer_explicit_tuple_wrapper",
        "tcpoly_infer_implicit_tuple_wrapper",
        "tcpoly_infer_ticket1864",
        "tcpoly_infer_ticket716",
        "tcpoly_seq",
        "tcpoly_seq_typealias",
        "tcpoly_ticket2096",
        "tcpoly_typeapp",
        "tcpoly_variance_pos",
        "test4",
        "test4a",
        "test5",
        "ticket0137",
        "ticket2197",
        "tinondefcons",
        "traits_1",
        "Transactions",
        "tryTyping",
        "tuplePatDef",
        "typeclass-encoding",
        "typeclass-encoding2",
        "unapplyComplex",
        "unicode-decode",
        "varargs",
        "virtpatmat_exist4",
        "virtpatmat_instof_valuetype",
        "virtpatmat_obj_in_case",
        "xml-pos",
        "z1720",
        "z1730",


        // Stack overflows
        "f-bounded-case-class",

        // Fails in bootstrapped only
        "i1500",
        "i2104",
        "i1540",
        "t1185",
        "t5779-numeq-warn",
        "t2405",
        "i1540b",
        "i1960",
        "i1751",
      )
    ).checkCompile()
  }

  @Test def runTestFromTasty: Unit = {
    // Can be reproduced with
    // > sbt
    // > dotc -Ythrough-tasty -Ycheck:all <source>
    // > dotr Test

    implicit val testGroup: TestGroup = TestGroup("runTestFromTasty")
    compileTastyInDir("tests/run", defaultOptions,
      blacklist = Set(
        // Closure type miss match
        "eff-dependent.scala",
      ),
      decompilationBlacklist = Set(
        // asTerm called on not-a-Term val <none>
        "t5045.scala",
        "mixins.scala",
        "t6666a.scala",
        "t4777.scala",
        "t6957.scala",
        "t8177f.scala",
        "Course-2002-06.scala",
        "implicits_poly.scala",
        "tcpoly_parseridioms.scala",
        "t4062.scala",
        "paramForwarding.scala",
        "t6506.scala",
        "i1692.scala",
        "caseclasses.scala",
        "i2883.scala",
        "t6793.scala",
        "i2163.scala",
        "planets.scala",
        "view-iterator-stream.scala",
        "enums.scala",
        "NestedClasses.scala",
        "paramForwarding_together.scala",
        "paramForwarding_together_b.scala",
        "t629.scala",
        "i763.scala",
        "t0883.scala",
        "absoverride.scala",
        "t3048.scala",
        "t3619.scala",
        "t3651.scala",
        "protectedacc.scala",
        "t7436.scala",

        // Constant(Symbol)
        "fors.scala",
        "t6634.scala",
        "t6632.scala",
        "t4601.scala",
        "t6633.scala",
        "arrays.scala",

        // scala.MatchError: SeqLiteral in pattern
        "i3248.scala",
        "t6541.scala",

        // scala.MatchError: This
        "t6104.scala",

      ),
      recompilationBlacklist = Set(
        "adding-growing-set",
        "applydynamic_sip",
        "array-addition",
        "array-charSeq",
        "bitsets",
        "builder",
        "capturing",
        "case-class-23",
        "case-class-toString",
        "caseClassHash",
        "CollectionTests",
        "colltest1",
        "concurrent-map-conversions",
        "config",
        "correct-bind",
        "Course-2002-03",
        "Course-2002-08",
        "Course-2002-13",
        "delambdafy-dependent-on-param-subst",
        "delambdafy-dependent-on-param-subst-2",
        "distinct",
        "duplicate-meth",
        "enrich-gentraversable",
        "enum-approx",
        "enum-HList",
        "enum-List1",
        "enum-List2",
        "enum-List2a",
        "enum-Option",
        "enum-Option1",
        "enum-Tree",
        "equality",
        "erased-17",
        "erased-18",
        "erased-19",
        "erased-2",
        "erased-20",
        "erased-21",
        "erased-23",
        "erased-3",
        "erased-4",
        "erased-machine-state",
        "erased-value-class",
        "exoticnames",
        "flat-flat-flat",
        "forvaleq",
        "forwarder",
        "fully-abstract-nat",
        "fully-abstract-nat-2",
        "fully-abstract-nat-4",
        "fully-abstract-nat-5",
        "fully-abstract-nat-6",
        "fully-abstract-nat-7",
        "function-arity",
        "getclass",
        "hashset",
        "hmap",
        "hmap-covariant",
        "i1354",
        "i1463",
        "i1503",
        "i1748",
        "i1773",
        "i1779",
        "i2360",
        "i2642",
        "i2795",
        "i2808",
        "i2895a",
        "i2916",
        "i3189",
        "i3448",
        "i4073",
        "i4073b",
        "i4073c",
        "i4558",
        "i4559",
        "i4600",
        "i756",
        "i768",
        "implicitFunctionXXL",
        "implicitFuns",
        "indexedSeq",
        "inline-implicits",
        "inline-object",
        "inlineByName",
        "inlinedAssign",
        "inlinePrivates",
        "inlineProtected",
        "interpolation-opt",
        "iterator-from",
        "lazy-exprs",
        "lazy-implicit-lists",
        "lazy-implicit-nums",
        "liftedTry",
        "map_java_conversions",
        "Meter",
        "MeterCaseClass",
        "mixin-bridge-methods",
        "mixin-primitive-on-generic-1",
        "mixin-primitive-on-generic-3",
        "mixin-primitive-on-generic-4",
        "mutable-treeset",
        "no-useless-forwarders",
        "nothing-lazy-val",
        "nothing-val",
        "nothing-var",
        "null-and-intersect",
        "null-hash",
        "null-lazy-val",
        "null-val",
        "null-var",
        "overloads",
        "patmat-bind-typed",
        "pc-conversions",
        "phantom-OnHList",
        "predef-cycle",
        "protectedSuper",
        "quote-simple-hole",
        "returning",
        "runtime",
        "search",
        "supercalls-traits",
        "t0017",
        "t1335",
        "t1360",
        "t1591",
        "t2029",
        "t2250",
        "t2594_tcpoly",
        "t261",
        "t2788",
        "t2867",
        "t3199b",
        "t3346g",
        "t3353",
        "t3361",
        "t3603",
        "t3613",
        "t4024",
        "t405",
        "t4288",
        "t4536",
        "t4582",
        "t4608",
        "t4761",
        "t4813",
        "t4835",
        "t4935",
        "t4996",
        "t5053",
        "t5201",
        "t5375",
        "t5532",
        "t5614",
        "t5648",
        "t5688",
        "t5733",
        "t5867",
        "t5879",
        "t6052",
        "t6111",
        "t6220",
        "t6260-delambdafy",
        "t6261",
        "t6290",
        "t6410",
        "t6443-varargs",
        "t6467",
        "t6488",
        "t6611",
        "t6908",
        "t7120b",
        "t7181",
        "t7214",
        "t7242",
        "t7475b",
        "t7571",
        "t7584",
        "t7584b",
        "t7899",
        "t8010",
        "t8087",
        "t8346",
        "t8395",
        "t8931",
        "tcpoly_monads",
        "traitNoInit",
        "traitParams",
        "try",
        "tryPatternMatch",
        "tuples",
        "typelevel",
        "unit-lazy-val",
        "unit-val",
        "unit-var",
        "unit-volatile-var",
        "unit_erasure",
        "unittest_iterator",
        "value-class-extractor",
        "value-class-extractor-2",
        "valueclasses-nested-object",
        "variable-pattern-access",
        "view-headoption",
        "viewtest",
        "virtpatmat_stringinterp",
        "virtpatmat_valdef",
        "withIndex",

        // Fails in bootstrapped only
        "t1500c",
        "is-valid-num",
        "nestedEq",
        "i2156",
        "i2508",
        "numbereq",
        "t6225",
        "t3699",
        "t3502",
        "t2316_run",
        "lambda-unit",
        "i1099",
        "ReplacementMatching",
        "t1500b",
        "i2895",
        "t6385",
        "enum-Color",
        "lift-and-unlift",
        "i4177",
        "t6337a",
        "t6150",
        "bigDecimalTest",
        "t3887",
        "OrderingTest",
        "serialize",
        "i1284",
        "scala2mixins",
        "i4446",
        "t3511",
        "double-pattern-type",
        "duration-coarsest",
        "iq",
        "i3624",
        "t6559",
        "LazyValsLongs",
        "t3235-minimal",
        "t2958",
        "ordered",
        "t1434",
        "t3714",
        "t751",
        "t2809",
        "t7278",
        "t4954",
        "t2087-and-2400",
        "t3518",
        "arrayview",
        "t4147",
        "t4558",
        "t4201",
        "t3540",
        "t5857",
        "t2378",
        "t4297",
        "transform",
        "stringbuilder-drop",
        "t4660",
        "t3493",
        "collections-toSelf",
        "zero-arity-case-class",
        "mapValues",
        "t3829",
        "t3647",
        "t8188",
        "groupby",
        "t1829",
        "bigDecimalCache",
        "t6292",
        "i1915",
        "stream-stack-overflow-filter-map",
        "drop-no-effects",
        "t266",
        "richWrapperEquals",
        "lambda-null",
        "patch-boundary",
        "t5665",
        "kmpSliceSearch",
        "t3563",
        "t4895",
        "t3923",
        "t3760",
        "t4894",
        "numeric-range",
        "t3970",
        "t4809",
        "slice-strings",
        "iterator3444",
        "t3529",
        "takeAndDrop",
        "t4723",
        "t4054",
        "t4398",
        "patmat-option-named",
        "t1697",
        "scan",
        "t3508",
        "t8680",
        "t3487",
        "t8738",
        "t3273",
        "t3645",
        "i1960",
        "t2524",
        "functionXXL",
        "t4122",
        "tuple-zipped",
        "i4430",
        "slices",

        "dynamicDynamicTests",
        "quote-compile-constants",

        // Stack overflow
        "t5009",
        "large2",
      )
    ).checkRuns()
  }
}

object FromTastyTests {
  implicit val summaryReport: SummaryReporting = new SummaryReport
  @AfterClass def cleanup(): Unit = summaryReport.echoSummary()
}
